name: "Get & cache Dependencies."
description: 'Getthe dependencies and (via pip) and cache them.'
runs:
  using: 'composite'
  steps:
    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash
    - name: Set up dependency caching for faster installs
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      shell: bash 